# Plagiarism Detection Model

Now that you've created training and test data, you are ready to define and train a model. Your goal in this notebook, will be to train a binary classification model that learns to label an answer file as either plagiarized or not, based on the features you provide the model.

This task will be broken down into a few discrete steps:

* Upload your data to S3.
* Define a binary classification model and a training script.
* Train your model and deploy it.
* Evaluate your deployed classifier and answer some questions about your approach.

To complete this notebook, you'll have to complete all given exercises and answer all the questions in this notebook.
> All your tasks will be clearly labeled **EXERCISE** and questions as **QUESTION**.

It will be up to you to explore different classification models and decide on a model that gives you the best performance for this dataset.

---

## Load Data to S3

In the last notebook, you should have created two files: a `training.csv` and `test.csv` file with the features and class labels for the given corpus of plagiarized/non-plagiarized text data. 

>The below cells load in some AWS SageMaker libraries and creates a default bucket. After creating this bucket, you can upload your locally stored data to S3.

Save your train and test `.csv` feature files, locally. To do this you can run the second notebook "2_Plagiarism_Feature_Engineering" in SageMaker or you can manually upload your files to this notebook using the upload icon in Jupyter Lab. Then you can upload local files to S3 by using `sagemaker_session.upload_data` and pointing directly to where the training data is saved.

In [1]:
import pandas as pd
import boto3
import sagemaker

In [2]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# session and role
sagemaker_session = sagemaker.Session()
role = sagemaker.get_execution_role()

# create an S3 bucket
bucket = sagemaker_session.default_bucket()

## EXERCISE: Upload your training data to S3

Specify the `data_dir` where you've saved your `train.csv` file. Decide on a descriptive `prefix` that defines where your data will be uploaded in the default S3 bucket. Finally, create a pointer to your training data by calling `sagemaker_session.upload_data` and passing in the required parameters. It may help to look at the [Session documentation](https://sagemaker.readthedocs.io/en/stable/session.html#sagemaker.session.Session.upload_data) or previous SageMaker code examples.

You are expected to upload your entire directory. Later, the training script will only access the `train.csv` file.

In [25]:
# should be the name of directory you created to save your features data
data_dir = 'plagiarism_data'

# set prefix, a descriptive name for a directory  
prefix = 'plagiarism_detection_data'

# upload all data to S3
plagiarism_data = sagemaker_session.upload_data(
    path=data_dir,
    bucket=bucket,
    key_prefix=prefix
)

### Test cell

Test that your data has been successfully uploaded. The below cell prints out the items in your S3 bucket and will throw an error if it is empty. You should see the contents of your `data_dir` and perhaps some checkpoints. If you see any other files listed, then you may have some old model files that you can delete via the S3 console (though, additional files shouldn't affect the performance of model developed in this notebook).

In [4]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# confirm that data is in S3 bucket
empty_check = []
for obj in boto3.resource('s3').Bucket(bucket).objects.all():
    empty_check.append(obj.key)
    print(obj.key)

assert len(empty_check) !=0, 'S3 bucket is empty.'
print('Test passed!')

counties/kmeans-2021-01-25-00-45-17-414/output/model.tar.gz
counties/kmeans-2021-01-25-00-45-17-414/profiler-output/framework/training_job_end.ts
counties/kmeans-2021-01-25-00-45-17-414/profiler-output/system/incremental/2021012500/1611535620.algo-1.json
counties/kmeans-2021-01-25-00-45-17-414/profiler-output/system/incremental/2021012500/1611535680.algo-1.json
counties/kmeans-2021-01-25-00-45-17-414/profiler-output/system/training_job_end.ts
counties/kmeans-2021-01-25-00-45-17-414/rule-output/ProfilerReport-1611535517/profiler-output/profiler-report.html
counties/kmeans-2021-01-25-00-45-17-414/rule-output/ProfilerReport-1611535517/profiler-output/profiler-report.ipynb
counties/kmeans-2021-01-25-00-45-17-414/rule-output/ProfilerReport-1611535517/profiler-output/profiler-reports/BatchSize.json
counties/kmeans-2021-01-25-00-45-17-414/rule-output/ProfilerReport-1611535517/profiler-output/profiler-reports/CPUBottleneck.json
counties/kmeans-2021-01-25-00-45-17-414/rule-output/ProfilerReport

---

# Modeling

Now that you've uploaded your training data, it's time to define and train a model!

The type of model you create is up to you. For a binary classification task, you can choose to go one of three routes:
* Use a built-in classification algorithm, like LinearLearner.
* Define a custom Scikit-learn classifier, a comparison of models can be found [here](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html).
* Define a custom PyTorch neural network classifier. 

It will be up to you to test out a variety of models and choose the best one. Your project will be graded on the accuracy of your final model. 
 
---

## EXERCISE: Complete a training script 

To implement a custom classifier, you'll need to complete a `train.py` script. You've been given the folders `source_sklearn` and `source_pytorch` which hold starting code for a custom Scikit-learn model and a PyTorch model, respectively. Each directory has a `train.py` training script. To complete this project **you only need to complete one of these scripts**; the script that is responsible for training your final model.

A typical training script:
* Loads training data from a specified directory
* Parses any training & model hyperparameters (ex. nodes in a neural network, training epochs, etc.)
* Instantiates a model of your design, with any specified hyperparams
* Trains that model 
* Finally, saves the model so that it can be hosted/deployed, later

### Defining and training a model
Much of the training script code is provided for you. Almost all of your work will be done in the `if __name__ == '__main__':` section. To complete a `train.py` file, you will:
1. Import any extra libraries you need
2. Define any additional model training hyperparameters using `parser.add_argument`
2. Define a model in the `if __name__ == '__main__':` section
3. Train the model in that same section

Below, you can use `!pygmentize` to display an existing `train.py` file. Read through the code; all of your tasks are marked with `TODO` comments. 

**Note: If you choose to create a custom PyTorch model, you will be responsible for defining the model in the `model.py` file,** and a `predict.py` file is provided. If you choose to use Scikit-learn, you only need a `train.py` file; you may import a classifier from the `sklearn` library.

In [5]:
# directory can be changed to: source_sklearn or source_pytorch
!pygmentize source_pytorch/train.py

import argparse
import json
import os
import pandas as pd
import torch
import torch.optim as optim
import torch.utils.data
from torch.nn import BCELoss

# imports the model in model.py by name
from model import BinaryClassifier

def model_fn(model_dir):
    """Load the PyTorch model from the `model_dir` directory."""
    print("Loading model.")

    # First, load the parameters used to create the model.
    model_info = {}
    model_info_path = os.path.join(model_dir, 'model_info.pth')
    with open(model_info_path, 'rb') as f:
        model_info = torch.load(f)

    print("model_info: {}".format(model_info))

    # Determine the device and construct the model.
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = BinaryClassifier(model_info['input_features'], model_info['hidden_dim'], model_info['output_dim'])

    # Load the stored model parameters.
    model_path = os.path.join(model_dir, 'model.pth')
    with open(model_path, 'rb') as f:
        mode

### Provided code

If you read the code above, you can see that the starter code includes a few things:
* Model loading (`model_fn`) and saving code
* Getting SageMaker's default hyperparameters
* Loading the training data by name, `train.csv` and extracting the features and labels, `train_x`, and `train_y`

If you'd like to read more about model saving with [joblib for sklearn](https://scikit-learn.org/stable/modules/model_persistence.html) or with [torch.save](https://pytorch.org/tutorials/beginner/saving_loading_models.html), click on the provided links.

---
# Create an Estimator

When a custom model is constructed in SageMaker, an entry point must be specified. This is the Python file which will be executed when the model is trained; the `train.py` function you specified above. To run a custom training script in SageMaker, construct an estimator, and fill in the appropriate constructor arguments:

* **entry_point**: The path to the Python script SageMaker runs for training.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **role**: Role ARN, which was specified, above.
* **train_instance_count**: The number of training instances (should be left at 1).
* **train_instance_type**: The type of SageMaker instance for training. Note: Because Scikit-learn does not natively support GPU training, Sagemaker Scikit-learn does not currently support training on GPU instance types.
* **sagemaker_session**: The session used to train on Sagemaker.
* **hyperparameters** (optional): A dictionary `{'name':value, ..}` passed to the train function as hyperparameters.

Note: For a PyTorch model, there is another optional argument **framework_version**, which you can set to the latest version of PyTorch, `1.0`.

## EXERCISE: Define a Scikit-learn or PyTorch estimator

To import your desired estimator, use one of the following lines:
```
from sagemaker.sklearn.estimator import SKLearn
```
```
from sagemaker.pytorch import PyTorch
```

In [54]:
'''
First tried PyTorch but did not get great results.

from sagemaker.pytorch import PyTorch

# your import and estimator code, here
estimator = PyTorch(
    entry_point='train.py',
    source_dir='source_pytorch',
    instance_type='ml.c4.xlarge',
    instance_count=1,
    role=role,
    sagemaker_session=sagemaker_session,
    framework_version='1.5.0',
    py_version='py3',
    hyperparameters = {
        'epochs':200,
        'batch-size':64,
    }
)'''

# Went with the LinearLearner that we used during the credit card fraud detection exercise

from sagemaker import LinearLearner

prefix = 'plagiarism_detection_data'
output_path = 's3://{}/{}'.format(bucket, prefix)

# instantiate LinearLearner
linear = LinearLearner(role=role,
                       instance_count=1, 
                       instance_type='ml.c4.xlarge',
                       predictor_type='binary_classifier',
                       output_path=output_path,
                       sagemaker_session=sagemaker_session,
                       epochs=15)

In [59]:
# Use provided code for test data below to pull the train data
import os

# read in test data, assuming it is stored locally
train_data = pd.read_csv(os.path.join(data_dir, "train.csv"), header=None, names=None)

# labels are in the first column
train_y = train_data.iloc[:,0]
train_x = train_data.iloc[:,1:]

# convert features/labels to numpy
train_x_np = train_x.astype('float32')
train_y_np = train_y.astype('float32')

# create RecordSet
formatted_train_data = linear.record_set(train_x_np.values, labels=train_y_np.values)

## EXERCISE: Train the estimator

Train your estimator on the training data stored in S3. This should create a training job that you can monitor in your SageMaker console.

In [60]:
%%time

# Train your estimator on S3 training data
#estimator.fit({
#    'train': plagiarism_data,
#})

# train the estimator on formatted training data
linear.fit(formatted_train_data)


Defaulting to the only supported framework/algorithm version: 1. Ignoring framework/algorithm version: 1.
Defaulting to the only supported framework/algorithm version: 1. Ignoring framework/algorithm version: 1.


2021-02-19 01:23:11 Starting - Starting the training job...
2021-02-19 01:23:35 Starting - Launching requested ML instancesProfilerReport-1613697791: InProgress
......
2021-02-19 01:24:36 Starting - Preparing the instances for training.........
2021-02-19 01:26:03 Downloading - Downloading input data
2021-02-19 01:26:03 Training - Training image download completed. Training in progress.Docker entrypoint called with argument(s): train
Running default environment configuration script
[02/19/2021 01:26:07 INFO 140209825703744] Reading default configuration from /opt/amazon/lib/python2.7/site-packages/algorithm/resources/default-input.json: {u'loss_insensitivity': u'0.01', u'epochs': u'15', u'feature_dim': u'auto', u'init_bias': u'0.0', u'lr_scheduler_factor': u'auto', u'num_calibration_samples': u'10000000', u'accuracy_top_k': u'3', u'_num_kv_servers': u'auto', u'use_bias': u'true', u'num_point_for_scaler': u'10000', u'_log_level': u'info', u'quantile': u'0.5', u'bias_lr_mult': u'auto', u


2021-02-19 01:26:58 Uploading - Uploading generated training model
2021-02-19 01:26:58 Completed - Training job completed
Training seconds: 71
Billable seconds: 71
CPU times: user 624 ms, sys: 39.3 ms, total: 664 ms
Wall time: 4min 12s


## EXERCISE: Deploy the trained model

After training, deploy your model to create a `predictor`. If you're using a PyTorch model, you'll need to create a trained `PyTorchModel` that accepts the trained `<model>.model_data` as an input parameter and points to the provided `source_pytorch/predict.py` file as an entry point. 

To deploy a trained model, you'll use `<model>.deploy`, which takes in two arguments:
* **initial_instance_count**: The number of deployed instances (1).
* **instance_type**: The type of SageMaker instance for deployment.

Note: If you run into an instance error, it may be because you chose the wrong training or deployment instance_type. It may help to refer to your previous exercise code to see which types of instances we used.

In [63]:
%%time

# uncomment, if needed
#from sagemaker.pytorch import PyTorchModel


# deploy your model to create a predictor
predictor = linear.deploy(
    initial_instance_count=1,
    instance_type='ml.t2.medium'
)

Defaulting to the only supported framework/algorithm version: 1. Ignoring framework/algorithm version: 1.


-------------------!CPU times: user 342 ms, sys: 16.4 ms, total: 358 ms
Wall time: 9min 32s


---
# Evaluating Your Model

Once your model is deployed, you can see how it performs when applied to our test data.

The provided cell below, reads in the test data, assuming it is stored locally in `data_dir` and named `test.csv`. The labels and features are extracted from the `.csv` file.

In [107]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import os

# read in test data, assuming it is stored locally
test_data = pd.read_csv(os.path.join(data_dir, "test.csv"), header=None, names=None)

# labels are in the first column
test_y = test_data.iloc[:,0]
test_x = test_data.iloc[:,1:]

# convert features/labels to numpy
test_x_np = np.array(test_x).astype('float32')
test_y_np = np.array(test_y).astype('float32')

In [108]:
print(np.array(test_x))

[[1.         0.90104167 0.82075472]
 [0.76530612 0.55363322 0.62171053]
 [0.88444444 0.15       0.59745763]
 [0.61904762 0.02173913 0.42783505]
 [0.92       0.32857143 0.775     ]
 [0.99267399 0.97014925 0.99305556]
 [0.41269841 0.         0.34666667]
 [0.46268657 0.         0.18932039]
 [0.58115183 0.         0.24742268]
 [0.58421053 0.         0.29441624]
 [0.56637168 0.         0.25833333]
 [0.48148148 0.00769231 0.27891156]
 [0.61979167 0.02139037 0.34158416]
 [0.92173913 0.6        0.92941176]
 [1.         0.90272374 1.        ]
 [0.86153846 0.04210526 0.50471698]
 [0.62616822 0.17088608 0.55855856]
 [1.         0.9609375  0.99669967]
 [0.38383838 0.00518135 0.17874396]
 [1.         0.92962963 0.85467128]
 [0.61392405 0.         0.29834254]
 [0.97276265 0.79365079 0.92708333]
 [0.96280992 0.64135021 0.90980392]
 [0.41525424 0.         0.17741935]
 [0.53218884 0.01315789 0.24583333]]


## EXERCISE: Determine the accuracy of your model

Use your deployed `predictor` to generate predicted, class labels for the test data. Compare those to the *true* labels, `test_y`, and calculate the accuracy as a value between 0 and 1.0 that indicates the fraction of test data that your model classified correctly. You may use [sklearn.metrics](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) for this calculation.

**To pass this project, your model should get at least 90% test accuracy.**

In [109]:
import numpy as np

# First: generate predicted, class labels
# Float64 Dataframe needs to be converted to Float32
test_y_preds = predictor.predict(test_x_np)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test that your model generates the correct number of labels
assert len(test_y_preds)==len(test_y), 'Unexpected number of predictions.'
print('Test passed!')

Test passed!


In [110]:
# Update predictions to be in the format we need

# LinearLearner produces a `predicted_label` for each data point in a batch
# get the 'predicted_label' for every point in a batch
test_y_preds = np.array([x.label['predicted_label'].float32_tensor.values[0] for x in test_y_preds])
print(test_y_preds)

[1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0.
 0.]


In [111]:
from sklearn.metrics import accuracy_score

# Second: calculate the test accuracy
accuracy = accuracy_score(test_y, test_y_preds)

print(accuracy)

## print out the array of predicted and true labels, if you want
print('\nPredicted class labels: ')
print(test_y_preds)
print('\nTrue class labels: ')
print(test_y.values)

1.0

Predicted class labels: 
[1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0.
 0.]

True class labels: 
[1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0.
 0.]


### Question 1: How many false positives and false negatives did your model produce, if any? And why do you think this is?

** Answer**: 
The model produced 0 false positives and false negatives. Perhaps something like plagiarism is much easier to detect than something like payment fraud. The sample text was also relatively small (not pages and pages long) so it's likely much easier to detect this type of plagiarism, positive or negative, when you're dealing with a less complicated set of text.


### Question 2: How did you decide on the type of model to use? 

** Answer**:

I first tried to use PyTorch with the Binary Classifier. Even after training it on 200 epochs with a batch size of 64 (found some answers around that batch size is better if it is in that range; i.e. https://discuss.pytorch.org/t/generic-question-about-batch-sizes/1321) I could only get the accuracy up to 40%

I then tried the LinearLearner and it worked much better. Looking back on the course so far, it would have made the most sense to start with the LinearLearner as it was used in an example we had previously in regards to payment fraud. With payment fraud, it is classified in a binary fashion (true or false) so the use case is very similiar to how we are attempting to detect plagiarism. It makes sense then that this method would be optimized for this use case.



----
## EXERCISE: Clean up Resources

After you're done evaluating your model, **delete your model endpoint**. You can do this with a call to `.delete_endpoint()`. You need to show, in this notebook, that the endpoint was deleted. Any other resources, you may delete from the AWS console, and you will find more instructions on cleaning up all your resources, below.

In [112]:
# uncomment and fill in the line below!
predictor.delete_endpoint()


### Deleting S3 bucket

When you are *completely* done with training and testing models, you can also delete your entire S3 bucket. If you do this before you are done training your model, you'll have to recreate your S3 bucket and upload your training data again.

In [113]:
# deleting bucket, uncomment lines below

#bucket_to_delete = boto3.resource('s3').Bucket(bucket)
#bucket_to_delete.objects.all().delete()

### Deleting all your models and instances

When you are _completely_ done with this project and do **not** ever want to revisit this notebook, you can choose to delete all of your SageMaker notebook instances and models by following [these instructions](https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-cleanup.html). Before you delete this notebook instance, I recommend at least downloading a copy and saving it, locally.

---
## Further Directions

There are many ways to improve or add on to this project to expand your learning or make this more of a unique project for you. A few ideas are listed below:
* Train a classifier to predict the *category* (1-3) of plagiarism and not just plagiarized (1) or not (0).
* Utilize a different and larger dataset to see if this model can be extended to other types of plagiarism.
* Use language or character-level analysis to find different (and more) similarity features.
* Write a complete pipeline function that accepts a source text and submitted text file, and classifies the submitted text as plagiarized or not.
* Use API Gateway and a lambda function to deploy your model to a web application.

These are all just options for extending your work. If you've completed all the exercises in this notebook, you've completed a real-world application, and can proceed to submit your project. Great job!